name: example_graphx
description: Graphx rendering prototype examples

publish_to: "none"

version: 1.0.10+37

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_svg: ^1.0.3
  
  url_launcher: ^6.1.8

  graphx:
    path: ../
  go_router: ^6.0.6
  flutter_blurhash: ^0.7.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter 

flutter:
  uses-material-design: true
  shaders:
      - shaders/colorful.frag

  assets: 
    - assets/
    - assets/thumbs/
    - assets/fb_reactions/
    - assets/bookmark_button/
    - assets/card_rotation/
    - assets/xmas/
    - assets/murat_coffee/
    - assets/run_hero/
    - assets/run_hero/parallax/
    - assets/heart_reaction/
    - assets/pizza_box/
    - assets/isma_chart/
    - assets/trigrid/
    - assets/globe_3d/

  fonts:
    - family: pressstart
      fonts:
        - asset: assets/fonts/pressstart.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700  
