name: graphx
description: Render API on top of CustomPainter to power-up your Flutter apps to the next level.
version: 1.0.2
homepage: https://github.com/roipeker/graphx

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^5.2.0
  http: ^0.13.3
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
