name: graphx
description: Render API on top of CustomPainter to power-up your Flutter apps to the next level.
version: 1.0.4
homepage: https://github.com/roipeker/graphx

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.1.0
  http: ^0.13.4
  flutter_svg: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
